sonar.qualitygate.wait=true
sonar.sources=src/main/java,src/main/resources,frontend/src
sonar.tests=src/test/java,frontend/tests
sonar.exclusions=frontend/dist/**,frontend/node_modules/**,target/**,uploads/**
sonar.coverage.exclusions=src/main/java/com/example/monkey/MonkeyShopApplication.java,src/main/resources/**,frontend/src/main.ts,frontend/src/router/**
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.spotbugs.reportPaths=target/spotbugsXml.xml
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
