spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

management:
  endpoint:
    env:
      show-values: NEVER
