{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "monkeyshop.namespaceName" . }}
  labels:
    {{- toYaml .Values.namespace.labels | nindent 4 }}
{{- end }}

