{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "monkeyshop.fullname" . }}
  labels:
    {{- include "monkeyshop.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "monkeyshop.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.prometheusNamespaceSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.mysqlNamespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.mysqlPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.mysql.port }}
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.redisNamespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.redisPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.redis.port }}
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.clamavNamespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.clamavPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.clamav.port }}
    - to:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.otelNamespaceSelector | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.otelPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: 4318
    - to:
        {{- range .Values.networkPolicy.externalHttpsCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 443
{{- end }}

