CREATE TABLE logistics_tracking (
    id BIGINT NOT NULL,
    tracking_no VARCHAR(64) NOT NULL,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    carrier VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    recipient_phone_ciphertext VARCHAR(1024),
    recipient_phone_hmac CHAR(64),
    address_ciphertext VARCHAR(2048),
    address_hmac CHAR(64),
    province VARCHAR(64),
    city VARCHAR(64),
    district VARCHAR(64),
    detail_summary VARCHAR(255),
    freight_amount DECIMAL(10, 2) NOT NULL,
    eta_hours INT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    picked_up_at DATETIME(6),
    in_transit_at DATETIME(6),
    out_for_delivery_at DATETIME(6),
    signed_at DATETIME(6),
    create_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    update_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_logistics_tracking_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT uk_logistics_tracking_no UNIQUE (tracking_no),
    CONSTRAINT uk_logistics_tracking_user_key UNIQUE (user_id, idempotency_key),
    CONSTRAINT ck_logistics_freight_amount CHECK (freight_amount >= 0),
    CONSTRAINT ck_logistics_eta_hours CHECK (eta_hours > 0),
    KEY idx_logistics_tracking_order_user (order_id, user_id),
    KEY idx_logistics_tracking_status_updated (status, update_time),
    KEY idx_logistics_tracking_phone_hmac (recipient_phone_hmac),
    KEY idx_logistics_tracking_address_hmac (address_hmac)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE logistics_tracking_event (
    id BIGINT NOT NULL,
    tracking_id BIGINT NOT NULL,
    tracking_no VARCHAR(64) NOT NULL,
    carrier VARCHAR(32) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    from_status VARCHAR(32) NOT NULL,
    to_status VARCHAR(32) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    event_time DATETIME(6) NOT NULL,
    location VARCHAR(128),
    remark VARCHAR(255),
    create_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_logistics_event_tracking FOREIGN KEY (tracking_id) REFERENCES logistics_tracking (id),
    CONSTRAINT uk_logistics_event_carrier_id UNIQUE (carrier, event_id),
    KEY idx_logistics_event_tracking_time (tracking_id, event_time),
    KEY idx_logistics_event_no_time (tracking_no, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE logistics_webhook_log (
    id BIGINT NOT NULL,
    carrier VARCHAR(32) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    tracking_no VARCHAR(64) NOT NULL,
    source_ip VARCHAR(64),
    create_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_logistics_webhook_carrier_event UNIQUE (carrier, event_id),
    KEY idx_logistics_webhook_tracking (tracking_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
